name: interactive_table
description: "A DataTable like Table with built in support for sticky headers, zoom and scroll"
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.19.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
